### ISSUE TITLE
disable swipe feature

### ISSUE THREAD

**Issue by wmanriques** [lucoceano/Pager#11]
In some cases I need to check the details from UITableView

**Comment by lfarah** [comment]
Hey @wmanriques, version `1.0.8` fixes that 😉

**Comment by wmanriques** [comment]
1.0.7 is the current version

**Comment by lfarah** [comment]
Just ran `pod install` and it is in `1.0.8` version
<img width="212" alt="screen shot 2016-07-21 at 9 16 52 pm" src="https://cloud.githubusercontent.com/assets/6511079/17042923/78e7f670-4f88-11e6-9ba8-e96716f3e6cc.png">

**Comment by anuraagdjain** [comment]
It's crashing on 1.0.8 . Fatal nil value found.
`topLayoutGuide += self.navigationController!.navigationBar.frame.size.height` , crash points to this location.
