### ISSUE TITLE
errors when compiling the project

### ISSUE THREAD

**Issue by odedharth** [lucoceano/Pager#14]
Getting bunch of errors - https://www.evernote.com/l/ADn0Vp91dwRN45Q-9Tz4yndbV4cRFOxaO48 when running the pod.
XCode 7.3, Swift 2.2

**Comment by lfarah** [comment]
Hey @odedharth, just pushed our version `1.0.7` to **CocoaPods**.
Let me know if it works!

**Comment by odedharth** [comment]
I'm not able to download it from cocoapods 

[!] Unable to satisfy the following requirements:
- `Pager (= 1.0.7)` required by `Podfile`

```
None of your spec sources contain a spec satisfying the dependency: `Pager (= 1.0.7)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

```

**Comment by lfarah** [comment]
We're on 1.0.8 now...

**Comment by lfarah** [comment]
@odedharth did it work?

**Comment by lfarah** [comment]
I'm gonna close it.. Lemme know if it doesn't work
