### ISSUE TITLE
detail view controller navigation problem

### ISSUE THREAD

**Issue by mrbayri** [lucoceano/Pager#18]
i have a navigation controller, i used tableview page in Pager. When i click tableviewcell navigation controller doesn't work, how to fix?

**Comment by keyanli** [comment]
I also have this problem. Same as tabBar viewcontroller, when I click tableviewcell, the tabbar is also not shown.

**Comment by lfarah** [comment]
I'm gonna look into that right now. Thanks for reporting!

**Comment by nsleche** [comment]
hey guys, i just submitted a PR adding a tableView with navigation to detail to the example project, if you guys can check and see if it may help you would be nice.

**Comment by lfarah** [comment]
@mrbayri, @keyanli any updates on that?

**Comment by lfarah** [comment]
Closing. Will reopen if any replies
