### ISSUE TITLE
Tabs beyond the 3rd tab aren't visible when using swipe gestures

### ISSUE THREAD

**Issue by ycastonguay-cbc** [lucoceano/Pager#2]
This code also has the same bugs as the CKViewPager, scrolling tabs quickly using swipe gestures will lead to a crash.

https://github.com/lucoceano/CKViewPager/issues/4

**Comment by lfarah** [comment]
Hey @ycastonguay-cbc, I just got permissions to Push to this repo, so you should see a lot of new updated in the next days. I'l take a look at your concern.

**Comment by lfarah** [comment]
@ycastonguay-cbc #4 updates the example app and now **you're able** to slide all the 7 tabs.
I noticed the crash and I'll take a look into that :wink:

**Comment by lfarah** [comment]
I'll close this issue and open a new one concerning the crashing:

> scrolling tabs quickly using swipe gestures will lead to a crash. lucoceano/CKViewPager#4
