### ISSUE TITLE
CenterCurrentTab not works

### ISSUE THREAD

**Issue by xipasx** [lucoceano/Pager#20]
When i set `centerCurrentTab = true` an active tab is not centered. How to fix? 

![simulator screen shot 14 8 2016 21 53 24](https://cloud.githubusercontent.com/assets/4195373/17651549/d4db3ef8-6269-11e6-9cdc-796fcbb037d1.png)

**Comment by nsleche** [comment]
which iOS version? 9.3 this property is working well for me.
<img width="374" alt="ss" src="https://cloud.githubusercontent.com/assets/11652045/17716120/46a81bc0-63bc-11e6-9340-48f5a3375439.png">

**Comment by xipasx** [comment]
I used iOS 9.3 and xcode 8 - beta 4. Maybe xcode is problem.

**Comment by lucoceano** [comment]
@xipasx I think is fixed, can you test?
