### ISSUE TITLE
About the TabBar hide, feel you judge some mistakes.

### ISSUE THREAD

**Issue by ChildrenGreens** [lucoceano/Pager#31]
if self.tabBarController != nil && self.tabBarController?.tabBar.isTranslucent == true {
    frame.size.height -= self.tabBarController!.tabBar.frame.height
}

Modified into

if self.tabBarController != nil && self.tabBarController?.tabBar.isTranslucent == false {
    frame.size.height -= self.tabBarController!.tabBar.frame.height
}

**Comment by lfarah** [comment]
@duanyicanyuan can you open a PR explaining about the improvement?
