### ISSUE TITLE
Error with using TabBarController

### ISSUE THREAD

**Issue by wayne1203** [lucoceano/Pager#32]
If I added TabBarController to the ViewController with Pager

I will got error in PagerController.swift Line 270 "var frame: CGRect = self.tabsView!.frame" 
fatal error: unexpectedly found nil while unwrapping an Optional value (lldb) 

Is it not support using TabBar??

**Comment by lfarah** [comment]
@nschucky can you help on this?

**Comment by nsleche** [comment]
@wayne1203 i added a tab bar to the example project, can you check if this is helpful? #33

**Comment by wayne1203** [comment]
@nschucky Thanks and I will check it after work. 😁

**Comment by wayne1203** [comment]
I checked #33 it's not problem.
Thank you for your help.

**Comment by schroederm** [comment]
@wayne1203 I'm having the same problem. Could you share your solution, please?

**Comment by schroederm** [comment]
For what it's worth, it helped me to call `self.defaultSetup()` after `self.setupPager()`.
