### ISSUE TITLE
Default Index

### ISSUE THREAD

**Issue by abhii24** [lucoceano/Pager#39]
can you please tell me how to scroll to a specific index at the start?

**Comment by lfarah** [comment]
@lucoceano any ideas?

**Comment by lfarah** [comment]
@nschucky ?

**Comment by lucoceano** [comment]
@lfarah @abhii24 I'll try something

**Comment by nschucky** [comment]
@abhii24  do you mean like this? or without the scrolling effect?
![scrolling](https://cloud.githubusercontent.com/assets/11652045/22994933/91ba14dc-f37d-11e6-8dd6-71557c6f2a53.gif)

**Comment by nsleche** [comment]
@abhii24 do you mean like this or without the scrolling effect?

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/11652045/22995446/ccbc5818-f37f-11e6-83ae-ef55c0f1030c.gif)

**Comment by abhii24** [comment]
no without any scrolling effect! suppose a user had bookmarked any index.Then he/she is supposed to be directed to that index kno when coming back @nschucky

**Comment by abhii24** [comment]
?? @lucoceano @nschucky

**Comment by abhii24** [comment]
Ok leave guys i have got the solution for it and its working like a charm thankyou 👍

**Comment by lucoceano** [comment]
@abhii24 I was gonna take an look right now, could you paste de solution here so when someone go looking for it they can find?

**Comment by abhii24** [comment]
I haven't done much of a code changees @lucoceano ..You have already given a method called "startFromSecondTab" ..Which goes like this - 
                var index: Int = self.startFromSecondTab ? 1 : 0
		self.selectTabAtIndex(index, swipe: true)

Whatever index i wanted to select as a starting index i had just passed it but only for the first time.

and in my class i have done "startFromSecondTab = True", for the first time or else  "startFromSecondTab = false" thats it
