### ISSUE TITLE
Delete a Index

### ISSUE THREAD

**Issue by abhii24** [lucoceano/Pager#43]
Can you please help me..how to delete any index on a button click? @lucoceano  @lfarah @FelipeDocil @pedrohperalta @xperi

**Comment by lucoceano** [comment]
@abhii24 did you find a solution? if so, could share with us?

**Comment by abhii24** [comment]
@lucoceano  i just had deleted that particular index From the viewControllers array and refreshed the view..but the problem is it takes me back to the index 0..!! can you please answer me to that issue related to default index that might help me!

**Comment by lucoceano** [comment]
@abhii24 nice, I'll have a look on the weekend
