### ISSUE TITLE
Is it possible to have fixed 2 non moving tabs?

### ISSUE THREAD

**Issue by jovanpreet** [lucoceano/Pager#45]
If i have 2 tabs initially both tabs are left aligned but as soon as i move to next tab the center property starts working. Even i set centerCurrentTab to false it still doesn't work

**Comment by abhii24** [comment]
Set centerCurrentTab = true
      fixFormerTabsPositions = false
      fixLaterTabsPosition = true 
and then try it! This might work for you @jovanpreet

**Comment by jovanpreet** [comment]
ok will try and let you know

**Comment by jovanpreet** [comment]
ok it worked. but any way to have selected tab image different from normal image

**Comment by abhii24** [comment]
@jovanpreet  i have to check for it. will let you know about it then

**Comment by jovanpreet** [comment]
ok

**Comment by nitishmakhija** [comment]
it doesn't work for me when I am selecting the second tab it automatically centers it
![ezgif com-optimize](https://cloud.githubusercontent.com/assets/18187743/24701787/7068a768-1a19-11e7-8e67-2abea363d785.gif)

**Comment by nitishmakhija** [comment]
centerCurrentTab = true
fixFormerTabsPositions = false
fixLaterTabsPosition = false


worked for me
