### ISSUE TITLE
Better description

### ISSUE THREAD

**Issue by lfarah** [lucoceano/Pager#5]
<img width="352" alt="screen shot 2016-03-11 at 11 13 00 am" src="https://cloud.githubusercontent.com/assets/6511079/13712745/4139f53c-e77a-11e5-89c9-808675b7fcc8.png">
I think the description could be

> Pager is the simplest and best way to implement sliding view controllers in Swift

**Comment by lfarah** [comment]
Hey @lucoceano, I don't have enough permissions to do this

**Comment by lfarah** [comment]
@lucoceano

**Comment by lucoceano** [comment]
@lfarah done!
